#!/usr/bin/env python3
"""
DDGS Search Demo - ReactAgent with Web Search and Report Generation

Demonstrates ReactAgent using the ddgs library for metasearch and
a report generator tool to create markdown reports from findings.

Two tools:
- ddgs_search: Web search via multiple engines
- generate_report: Create markdown report from content

Requirements:
- OPENAI_API_KEY environment variable set
- ddgs package installed (uv pip install ddgs)
"""

import asyncio
import os
from datetime import datetime

from dotenv import load_dotenv

from tinyagent import ReactAgent, tool

load_dotenv()


@tool
def ddgs_search(query: str, max_results: int = 5) -> str:
    """Search the web using DDGS metasearch.

    Aggregates results from multiple search engines (Google, Brave, DuckDuckGo, etc.).
    Use this first to gather information before generating a report.

    Args:
        query: The search query
        max_results: Maximum number of results to return (default 5)

    Returns:
        Formatted search results with titles, descriptions, and URLs
    """
    from ddgs import DDGS

    try:
        results = DDGS().text(
            query,
            region="us-en",
            safesearch="moderate",
            max_results=max_results,
            backend="auto",
        )

        if not results:
            return f"No results found for: {query}"

        formatted = []
        for i, r in enumerate(results, 1):
            title = r.get("title", "No title")
            body = r.get("body", "No description")
            href = r.get("href", "")
            formatted.append(f"{i}. {title}\n   {body}\n   URL: {href}")

        return "\n\n".join(formatted)

    except Exception as e:
        return f"Search error: {e}"


@tool
def generate_report(title: str, summary: str, key_points: str, sources: str) -> str:
    """Generate a markdown report from research findings.

    Use this after gathering information with ddgs_search to create
    a structured markdown report.

    Args:
        title: Report title
        summary: Executive summary (2-3 sentences)
        key_points: Main findings as bullet points (use | as separator)
        sources: Source URLs (use | as separator)

    Returns:
        Formatted markdown report
    """
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")

    # Parse key points and sources
    points = [p.strip() for p in key_points.split("|") if p.strip()]
    urls = [u.strip() for u in sources.split("|") if u.strip()]

    # Build markdown
    md = f"""# {title}

**Generated:** {timestamp}

## Summary

{summary}

## Key Findings

"""
    for point in points:
        md += f"- {point}\n"

    md += "\n## Sources\n\n"
    for i, url in enumerate(urls, 1):
        md += f"{i}. {url}\n"

    md += "\n---\n*Report generated by ReactAgent with DDGS*\n"

    return md


async def main():
    """Run the DDGS search and report demo."""
    print("=" * 80)
    print("DDGS Search Demo - Web Search + Report Generation")
    print("=" * 80)

    if not os.getenv("OPENAI_API_KEY"):
        print("ERROR: Set OPENAI_API_KEY environment variable")
        return

    agent = ReactAgent(
        tools=[ddgs_search, generate_report],
        model="gpt-4o-mini",
        temperature=0.3,
    )

    query = (
        "Research the ReAct pattern in AI agents. "
        "Search for information, then generate a markdown report "
        "with a summary, key findings, and sources."
    )

    print(f"\nTASK: {query}\n")
    print("=" * 80)

    try:
        result = await agent.run(query, verbose=True)

        # Save report to file
        report_path = "examples/report.md"
        with open(report_path, "w") as f:
            f.write(result)

        print(f"\n{'=' * 80}")
        print(f"REPORT SAVED TO: {report_path}")
        print("=" * 80)
        print(result)
    except Exception as e:
        print(f"\nERROR: {e}")


if __name__ == "__main__":
    asyncio.run(main())
