#!/usr/bin/env python3
"""
Hybrid Agent Demo - Combining ReactAgent and TinyCodeAgent

This example demonstrates how to use both agent types together:
- ReactAgent for web searches and external tools
- TinyCodeAgent for data analysis and computation
- Shared tools that work with both agents
- Memory persistence and signal usage

The use case: Research stock performance, analyze the data, and generate insights.
"""

import asyncio

from dotenv import load_dotenv

from tinyagent import ExecutionLimits, ReactAgent, TinyCodeAgent, TrustLevel, tool

load_dotenv()

# =============================================================================
# SHARED TOOLS - Work with both agents
# =============================================================================


@tool
def calculate_returns(prices: list[float]) -> list[float]:
    """Calculate daily returns from price list.

    Args:
        prices: List of closing prices

    Returns:
        List of daily percentage returns
    """
    returns = []
    for i in range(1, len(prices)):
        daily_return = ((prices[i] - prices[i - 1]) / prices[i - 1]) * 100
        returns.append(round(daily_return, 2))
    return returns


@tool
def volatility(returns: list[float]) -> float:
    """Calculate volatility (standard deviation of returns).

    Args:
        returns: List of daily returns

    Returns:
        Annualized volatility percentage
    """
    import math

    if len(returns) < 2:
        return 0.0

    mean = sum(returns) / len(returns)
    variance = sum((r - mean) ** 2 for r in returns) / (len(returns) - 1)
    std_dev = math.sqrt(variance)
    # Annualize (assuming daily returns)
    annualized = std_dev * math.sqrt(252)
    return round(annualized, 2)


@tool
def format_insights(
    stock: str, prices: list[float], returns: list[float], vol: float, analysis: str
) -> str:
    """Format a comprehensive investment analysis report.

    Args:
        stock: Stock ticker symbol
        prices: Price history
        returns: Calculated returns
        vol: Volatility score
        analysis: Python agent's analysis

    Returns:
        Formatted markdown report
    """
    current_price = prices[-1] if prices else 0
    price_change = returns[-1] if returns else 0

    report = f"""# {stock} Investment Analysis

## Price Performance
- Current Price: ${current_price:.2f}
- Daily Change: {price_change:+.2f}%
- Price Range: ${min(prices):.2f} - ${max(prices):.2f}

## Risk Metrics
- Volatility: {vol:.2f}% (annualized)
- Risk Level: {'High' if vol > 30 else 'Medium' if vol > 20 else 'Low'}

## Technical Analysis
{analysis}

---
*Generated by tinyAgent Hybrid System*
"""
    return report


# =============================================================================
# REACT-AGENT-SPECIFIC TOOLS
# =============================================================================


@tool
def web_search(query: str, max_results: int = 3) -> str:
    """Simulate web search for stock information (mock implementation).

    In a real implementation, this would use Brave Search API or similar.

    Args:
        query: Search query
        max_results: The maximum number of results to return

    Returns:
        Formatted search results
    """
    # Mock data for demonstration
    mock_results = [
        {
            "title": f"{query.split()[0]} Stock Analysis",
            "snippet": "Recent performance indicates strong growth potential with moderate risk...",
            "url": "https://example.com/analysis",
        },
        {
            "title": f"Market Trends for {query.split()[0]}",
            "snippet": "Technical indicators suggest bullish momentum in the short term...",
            "url": "https://example.com/trends",
        },
    ]

    formatted = []
    for i, result in enumerate(mock_results[:max_results], 1):
        formatted.append(f"{i}. {result['title']}")
        formatted.append(f"   {result['snippet']}")
        formatted.append(f"   URL: {result['url']}\n")

    return "\n".join(formatted)


# =============================================================================
# DEMO FUNCTIONS
# =============================================================================


async def react_agent_demo():
    """Demo ReactAgent for research and data gathering."""
    print("\n" + "=" * 60)
    print("🔍 REACTAGENT - Research & Data Gathering")
    print("=" * 60)

    tools = [web_search, calculate_returns, volatility]
    agent = ReactAgent(tools=tools, verbose=True)

    # Generate mock stock data
    mock_prices = [100, 102, 98, 105, 103, 107, 110, 108, 112, 115]

    task = f"""
    Research stock AAPL using available tools:
    1. Search for recent AAPL market analysis
    2. Calculate returns for this price data: {mock_prices}
    3. Compute volatility
    4. Research volatility implications
    5. Provide research summary
    """

    result = await agent.run(task, return_result=True)
    return result


async def tinycode_agent_demo():
    """Demo TinyCodeAgent for analysis and computation."""
    print("\n" + "=" * 60)
    print("🧮 TINYCODEAGENT - Deep Analysis & Computation")
    print("=" * 60)

    # Create analysis tools
    analysis_tools = [calculate_returns, volatility, format_insights]

    # Configure with memory and limits
    limits = ExecutionLimits(
        timeout_seconds=10,
        max_steps=8,
        max_output_bytes=5000,
    )

    agent = TinyCodeAgent(
        tools=analysis_tools,
        trust_level=TrustLevel.LOCAL,
        limits=limits,
        extra_imports=["math", "statistics"],
        verbose=True,
    )

    # Mock comprehensive data
    stock_data = {
        "stock": "NVDA",
        "prices": [500, 520, 510, 540, 530, 560, 580, 570, 590, 610],
        "context": "Tech sector, recent earnings beat expectations",
    }

    task = f"""
    Analyze this stock data using Python:

    Stock Information:
    - Symbol: {stock_data['stock']}
    - Price History: {stock_data['prices']}
    - Context: {stock_data['context']}

    Tasks:
    1. Calculate daily returns using calculate_returns()
    2. Compute volatility using volatility()
    3. Perform deeper statistical analysis (avg return, max gain/loss)
    4. Store intermediate results using memory()
    5. Generate final insights using format_insights()

    Think step by step. Store calculations in memory before final analysis.
    """

    result = await agent.run(task, return_result=True)
    return result


async def hybrid_workflow():
    """Complete workflow combining both agents for comprehensive analysis."""
    print("\n" + "=" * 60)
    print("🚀 HYBRID WORKFLOW - Complete Analysis Pipeline")
    print("=" * 60)

    # Step 1: ReactAgent gathers research data
    react_toolkit = [web_search]
    researcher = ReactAgent(tools=react_toolkit, verbose=False)

    print("\n📊 Step 1: Market Research (ReactAgent)")
    market_research = await researcher.run(
        "Get recent market analysis for TSLA stock, focusing on Q4 2023 performance"
    )
    print(f"Research Summary:\n{market_research[:300]}...")

    # Step 2: TinyCodeAgent performs deep analysis
    analysis_toolkit = [calculate_returns, volatility, format_insights]

    limits = ExecutionLimits(
        timeout_seconds=15,
        max_steps=10,
        max_output_bytes=8000,
    )

    analyst = TinyCodeAgent(
        tools=analysis_toolkit,
        trust_level=TrustLevel.LOCAL,
        limits=limits,
        extra_imports=["math", "statistics", "datetime"],
        verbose=False,
    )

    print("\n📈 Step 2: Technical Analysis (TinyCodeAgent)")

    # Simulated TSLA price data
    tsla_prices = [200, 205, 198, 210, 215, 208, 220, 225, 218, 230]

    analysis_task = f"""
    You are a financial analyst. Analyze TSLA stock comprehensively:

    Price Data: {tsla_prices}
    Research Context: Recent market research shows mixed signals

    Analysis Plan:
    1. Calculate technical indicators (returns, volatility, trend)
    2. Store calculations using memory for reference
    3. Perform statistical analysis (mean, median, std deviation)
    4. Identify key patterns and insights
    5. Generate investment recommendation with reasoning
    6. Create comprehensive report using format_insights()

    Use signal functions: uncertain() when analyzing patterns,
    explore() when testing hypotheses, commit() for final conclusions.
    """

    final_analysis = await analyst.run(analysis_task, return_result=True)

    print("\n📋 Final Hybrid Analysis Report:")
    print("=" * 60)
    print(final_analysis.output)
    print("\nExecution Stats:")
    print(f"- Steps taken: {final_analysis.steps_taken}")
    print(f"- Duration: {final_analysis.duration_seconds:.2f}s")
    print(f"- State: {final_analysis.state}")


# =============================================================================
# MAIN EXECUTION
# =============================================================================


async def main():
    """Run all demonstrations."""
    print("🤖 tinyAgent Hybrid Demonstration")
    print("Combining ReactAgent (research) + TinyCodeAgent (analysis)")

    try:
        # Individual demos
        react_result = await react_agent_demo()
        print(f"\n✅ ReactAgent completed in {react_result.duration_seconds:.2f}s")

        code_result = await tinycode_agent_demo()
        print(f"\n✅ TinyCodeAgent completed in {code_result.duration_seconds:.2f}s")

        # Hybrid workflow
        await hybrid_workflow()

        print("\n🎉 All demonstrations completed successfully!")

    except Exception as e:
        print(f"\n❌ Error: {e}")
        import traceback

        traceback.print_exc()


if __name__ == "__main__":
    asyncio.run(main())
